<script lang="ts">
	import { submitPlugin, uploadBuildPackage } from '$lib/api';
	import { goto } from '$app/navigation';
	import { Upload, PackageCheck, Link as LinkIcon, Shield, ShieldAlert } from 'lucide-svelte';
	import type { UploadedBuildResult } from '$lib/api';

	const permissions = [
		{ bit: 1 << 0, label: 'Read Messages', risky: false },
		{ bit: 1 << 1, label: 'Send Messages', risky: false },
		{ bit: 1 << 2, label: 'Manage Messages', risky: true },
		{ bit: 1 << 3, label: 'Read Members', risky: false },
		{ bit: 1 << 4, label: 'Manage Members', risky: true },
		{ bit: 1 << 5, label: 'Read Channels', risky: false },
		{ bit: 1 << 6, label: 'Manage Channels', risky: true },
		{ bit: 1 << 7, label: 'Add Channel Types', risky: false },
		{ bit: 1 << 8, label: 'Add Commands', risky: false },
		{ bit: 1 << 9, label: 'Server Info', risky: false },
		{ bit: 1 << 10, label: 'Webhooks', risky: true },
		{ bit: 1 << 11, label: 'React to Messages', risky: false }
	];

	let packageFile = $state<File | null>(null);
	let isUploadingPackage = $state(false);
	let packaged = $state<UploadedBuildResult | null>(null);
	let requestedPermissionsOverride = $state(0);

	let isSubmitting = $state(false);
	let error = $state('');

	function handlePackageSelect(event: Event) {
		const input = event.currentTarget as HTMLInputElement;
		packageFile = input.files?.[0] || null;
		packaged = null;
		requestedPermissionsOverride = 0;
	}

	async function uploadPackage() {
		if (!packageFile) return;

		error = '';
		packaged = null;
		isUploadingPackage = true;

		try {
			packaged = await uploadBuildPackage(packageFile);
			requestedPermissionsOverride = packaged.requestedPermissions ?? 0;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to upload package';
		} finally {
			isUploadingPackage = false;
		}
	}

	function togglePermission(bit: number) {
		requestedPermissionsOverride = requestedPermissionsOverride ^ bit;
	}

	async function handleSubmit() {
		error = '';

		if (!packaged) {
			error = 'Upload a build package first';
			return;
		}

		isSubmitting = true;
		try {
			await submitPlugin({
				slug: packaged.slug,
				name: packaged.name,
				description: packaged.description,
				author: packaged.author,
				version: packaged.version,
				homepageUrl: packaged.homepageUrl,
				sourceUrl: packaged.sourceUrl,
				iconUrl: packaged.iconUrl,
				requestedPermissions: requestedPermissionsOverride,
				manifest: packaged.manifest
			});
			goto('/');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to submit plugin';
		} finally {
			isSubmitting = false;
		}
	}
</script>

<svelte:head>
	<title>Submit Plugin - Zentra Plugin Marketplace</title>
</svelte:head>

<div class="max-w-2xl mx-auto px-6 py-8">
	<h1 class="text-3xl font-semibold tracking-tight mb-2">Publish Plugin</h1>
	<p class="text-(--text-muted) mb-6">Upload a packaged build. Metadata is read directly from the package manifest.</p>

	{#if error}
		<div class="p-3 mb-4 rounded-lg bg-(--danger)/10 border border-(--danger)/20 text-sm text-(--danger)">
			{error}
		</div>
	{/if}

	<div class="surface-panel rounded-xl p-4 mb-5 space-y-3">
		<div class="flex items-center gap-2 text-sm font-medium">
			<Upload size={16} class="text-(--accent)" />
			Compiled build package
		</div>
		<p class="text-xs text-(--text-muted)">
			Upload a `.zip` generated by `zentra-plugin package`. This hosts all build files in the marketplace and fills `manifest.frontendBundle` for you.
		</p>
		<div class="flex items-center gap-2">
			<input
				type="file"
				accept=".zip"
				onchange={handlePackageSelect}
				class="flex-1 text-sm file:mr-3 file:px-3 file:py-1.5 file:rounded-lg file:border-0 file:bg-(--bg-hover) file:text-(--text) file:cursor-pointer"
			/>
			<button
				type="button"
				onclick={uploadPackage}
				disabled={!packageFile || isUploadingPackage}
				class="px-4 py-2 bg-(--accent) text-[#03231b] font-medium rounded-lg hover:bg-(--accent-hover) transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
			>
				{isUploadingPackage ? 'Uploading…' : 'Upload Build'}
			</button>
		</div>
		{#if packaged}
			<div class="text-xs rounded-lg p-2 bg-(--accent-muted) text-(--text) border border-(--border-light) flex items-start gap-2">
				<PackageCheck size={14} class="mt-0.5 text-(--accent)" />
				<span>Package uploaded. Frontend bundle hosted at {packaged.frontendBundleUrl}</span>
			</div>
		{/if}
	</div>

	<form onsubmit={(e) => { e.preventDefault(); handleSubmit(); }} class="space-y-5 surface-panel rounded-xl p-5">
		{#if packaged}
			<div class="grid grid-cols-2 gap-4 text-sm">
				<div>
					<p class="text-(--text-muted)">Slug</p>
					<p class="font-medium">{packaged.slug}</p>
				</div>
				<div>
					<p class="text-(--text-muted)">Version</p>
					<p class="font-medium">{packaged.version}</p>
				</div>
				<div>
					<p class="text-(--text-muted)">Name</p>
					<p class="font-medium">{packaged.name || 'Unnamed plugin'}</p>
				</div>
				<div>
					<p class="text-(--text-muted)">Author</p>
					<p class="font-medium">{packaged.author || 'Unknown author'}</p>
				</div>
			</div>
			<p class="text-sm text-(--text-muted)">{packaged.description || 'No description provided in manifest.'}</p>

			<div class="mt-4 rounded-lg border border-(--border) p-3 bg-(--bg-soft)">
				<p class="text-sm font-medium mb-2">Requested permissions</p>
				<p class="text-xs text-(--text-muted) mb-3">Pick what this plugin can request during community installation.</p>
				<div class="grid gap-2">
					{#each permissions as permission}
						<label class="flex items-center gap-2 text-sm">
							<input
								type="checkbox"
								checked={(requestedPermissionsOverride & permission.bit) !== 0}
								onchange={() => togglePermission(permission.bit)}
								class="rounded border-(--border)"
							/>
							{#if permission.risky}
								<ShieldAlert size={14} class="text-yellow-400" />
							{:else}
								<Shield size={14} class="text-green-400" />
							{/if}
							<span>{permission.label}</span>
						</label>
					{/each}
				</div>
			</div>
		{:else}
			<p class="text-sm text-(--text-muted)">Upload a packaged build to preview manifest metadata and publish.</p>
		{/if}

		<div class="flex justify-end gap-3 pt-2 border-t border-(--border)">
			<a
				href="/"
				class="px-4 py-2 text-sm text-(--text-muted) hover:text-(--text) no-underline"
			>
				Cancel
			</a>
			<button
				type="submit"
				disabled={isSubmitting || !packaged}
				class="px-5 py-2 bg-(--accent) text-[#03231b] rounded-lg hover:bg-(--accent-hover) transition-colors font-medium text-sm disabled:opacity-50"
			>
				{isSubmitting ? 'Publishing...' : 'Publish Plugin'}
			</button>
		</div>
	</form>

	<div class="mt-5 text-xs text-(--text-muted) flex items-center gap-1.5">
		<LinkIcon size={13} />
		Bundle URLs are hosted under `/builds/{'{slug}'}/{'{version}'}/...` after upload.
	</div>
</div>
